// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/20/2026, 9:49:27 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/data/data/com.termux/files/home/storage/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/data/data/com.termux/files/home/storage/portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/data/data/com.termux/files/home/storage/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/data/data/com.termux/files/home/storage/portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/data/data/com.termux/files/home/storage/portfolio/plugins/**/*.{js,ts,mjs}","/data/data/com.termux/files/home/storage/portfolio/composables/**/*.{js,ts,mjs}","/data/data/com.termux/files/home/storage/portfolio/utils/**/*.{js,ts,mjs}","/data/data/com.termux/files/home/storage/portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/data/data/com.termux/files/home/storage/portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/data/data/com.termux/files/home/storage/portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/data/data/com.termux/files/home/storage/portfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;